#!/usr/bin/env bash

printf '%s\n' "${*}" >>"${CLASHCTL_FAKE_LOG}"
case "${1:-}" in
env)
    printf '%s\n' \
        'export http_proxy=http://127.0.0.1:17890' \
        'export HTTP_PROXY=http://127.0.0.1:17890' \
        'export https_proxy=http://127.0.0.1:17890' \
        'export HTTPS_PROXY=http://127.0.0.1:17890' \
        'export all_proxy=socks5h://127.0.0.1:17890' \
        'export ALL_PROXY=socks5h://127.0.0.1:17890' \
        'export no_proxy=localhost,127.0.0.1,::1' \
        'export NO_PROXY=localhost,127.0.0.1,::1'
    ;;
*) exit 0 ;;
esac
